version: "3.8"
services:
    sonarqube:
        image: sonarqube:lts-community
        ports:
            - "9000:9000"
        environment:
            # desabilita alguns checks de memória no container
            - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
    sonarqube_data:
    sonarqube_extensions:
