version: "3.8"

services:
    postgres:
        container_name: ese-tracking-db
        image: postgres:14.5
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ese-tracking-db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - rabbitmq_net

    app:
        container_name: ese-tracking-service
        build: .
        depends_on:
            - postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: ese-tracking-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PORT: 3001
            RABBITMQ_URL: amqp://rabbitmq
            QUEUE_NAME: delivery_appointments
        ports:
            - "3001:3001"
        command: node dist/main.js
        networks:
            - rabbitmq_net

volumes:
    postgres_data:

networks:
    rabbitmq_net:
        external: true
